// A large built-in catalog of common exercises, grouped by muscle group.
// These are suggestions only — nothing here is "real" until the user picks
// one, at which point Store.addExercise() creates it in their own data.
const EXERCISE_LIBRARY = [
  // Chest
  { name: "Bench Press (Barbell)", muscleGroup: "Chest" },
  { name: "Bench Press (Dumbbell)", muscleGroup: "Chest" },
  { name: "Bench Press (Smith Machine)", muscleGroup: "Chest" },
  { name: "Incline Bench Press (Barbell)", muscleGroup: "Chest" },
  { name: "Incline Bench Press (Dumbbell)", muscleGroup: "Chest" },
  { name: "Decline Bench Press (Barbell)", muscleGroup: "Chest" },
  { name: "Decline Bench Press (Dumbbell)", muscleGroup: "Chest" },
  { name: "Chest Fly", muscleGroup: "Chest" },
  { name: "Chest Fly (Dumbbell)", muscleGroup: "Chest" },
  { name: "Chest Fly (Machine)", muscleGroup: "Chest" },
  { name: "Incline Chest Fly (Dumbbell)", muscleGroup: "Chest" },
  { name: "Cable Crossover", muscleGroup: "Chest" },
  { name: "Pec Deck", muscleGroup: "Chest" },
  { name: "Chest Dip", muscleGroup: "Chest" },
  { name: "Push Up", muscleGroup: "Chest" },
  { name: "Incline Push Up", muscleGroup: "Chest" },
  { name: "Landmine Press", muscleGroup: "Chest" },
  { name: "Svend Press", muscleGroup: "Chest" },
  { name: "Floor Press (Barbell)", muscleGroup: "Chest" },

  // Back
  { name: "Pull Up", muscleGroup: "Back" },
  { name: "Chin Up", muscleGroup: "Back" },
  { name: "Neutral Grip Pull Up", muscleGroup: "Back" },
  { name: "Lat Pulldown (Cable)", muscleGroup: "Back" },
  { name: "Lat Pulldown (Machine)", muscleGroup: "Back" },
  { name: "Single Arm Lat Pulldown", muscleGroup: "Back" },
  { name: "Seated Row (Cable)", muscleGroup: "Back" },
  { name: "Seated Wide-Grip Row (Cable)", muscleGroup: "Back" },
  { name: "Chest Supported Row", muscleGroup: "Back" },
  { name: "Bent Over Row (Barbell)", muscleGroup: "Back" },
  { name: "Bent Over One Arm Row (Dumbbell)", muscleGroup: "Back" },
  { name: "Pendlay Row (Barbell)", muscleGroup: "Back" },
  { name: "T-Bar Row", muscleGroup: "Back" },
  { name: "Deadlift (Barbell)", muscleGroup: "Back" },
  { name: "Trap Bar Deadlift", muscleGroup: "Back" },
  { name: "Romanian Deadlift (Barbell)", muscleGroup: "Back" },
  { name: "Sumo Deadlift (Barbell)", muscleGroup: "Back" },
  { name: "Good Morning", muscleGroup: "Back" },
  { name: "Face Pull", muscleGroup: "Back" },
  { name: "Shrug (Barbell)", muscleGroup: "Back" },
  { name: "Shrug (Dumbbell)", muscleGroup: "Back" },
  { name: "Hyperextension", muscleGroup: "Back" },
  { name: "Straight Arm Pulldown", muscleGroup: "Back" },

  // Shoulders
  { name: "Shoulder Press (Barbell)", muscleGroup: "Shoulders" },
  { name: "Shoulder Press (Dumbbell)", muscleGroup: "Shoulders" },
  { name: "Shoulder Press (Machine)", muscleGroup: "Shoulders" },
  { name: "Shoulder Press (Plate Loaded)", muscleGroup: "Shoulders" },
  { name: "Arnold Press (Dumbbell)", muscleGroup: "Shoulders" },
  { name: "Military Press (Barbell)", muscleGroup: "Shoulders" },
  { name: "Push Press", muscleGroup: "Shoulders" },
  { name: "Lateral Raise (Dumbbell)", muscleGroup: "Shoulders" },
  { name: "Lateral Raise (Cable)", muscleGroup: "Shoulders" },
  { name: "Lateral Raise (Machine)", muscleGroup: "Shoulders" },
  { name: "Front Raise (Dumbbell)", muscleGroup: "Shoulders" },
  { name: "Front Raise (Barbell)", muscleGroup: "Shoulders" },
  { name: "Front Raise (Plate)", muscleGroup: "Shoulders" },
  { name: "Reverse Fly (Machine)", muscleGroup: "Shoulders" },
  { name: "Reverse Fly (Dumbbell)", muscleGroup: "Shoulders" },
  { name: "Reverse Fly (Cable)", muscleGroup: "Shoulders" },
  { name: "Upright Row (Cable)", muscleGroup: "Shoulders" },
  { name: "Upright Row (Barbell)", muscleGroup: "Shoulders" },
  { name: "Cable Y-Raise", muscleGroup: "Shoulders" },

  // Legs
  { name: "Squat (Barbell)", muscleGroup: "Legs" },
  { name: "Front Squat (Barbell)", muscleGroup: "Legs" },
  { name: "Box Squat (Barbell)", muscleGroup: "Legs" },
  { name: "Goblet Squat (Dumbbell)", muscleGroup: "Legs" },
  { name: "Sumo Squat", muscleGroup: "Legs" },
  { name: "Hack Squat", muscleGroup: "Legs" },
  { name: "Leg Press", muscleGroup: "Legs" },
  { name: "Leg Extension (Machine)", muscleGroup: "Legs" },
  { name: "Seated Leg Curl (Machine)", muscleGroup: "Legs" },
  { name: "Lying Leg Curl (Machine)", muscleGroup: "Legs" },
  { name: "Standing Calf Raise (Barbell)", muscleGroup: "Legs" },
  { name: "Standing Calf Raise (Machine)", muscleGroup: "Legs" },
  { name: "Seated Calf Raise (Machine)", muscleGroup: "Legs" },
  { name: "Bulgarian Split Squat", muscleGroup: "Legs" },
  { name: "Walking Lunge (Dumbbell)", muscleGroup: "Legs" },
  { name: "Lunge (Barbell)", muscleGroup: "Legs" },
  { name: "Reverse Lunge (Dumbbell)", muscleGroup: "Legs" },
  { name: "Step Up", muscleGroup: "Legs" },
  { name: "Hip Thrust (Barbell)", muscleGroup: "Legs" },
  { name: "Glute Bridge", muscleGroup: "Legs" },
  { name: "Hip Abductor (Machine)", muscleGroup: "Legs" },
  { name: "Hip Adductor (Machine)", muscleGroup: "Legs" },

  // Arms
  { name: "Bicep Curl (Barbell)", muscleGroup: "Arms" },
  { name: "Bicep Curl (Dumbbell)", muscleGroup: "Arms" },
  { name: "Bicep Curl (Cable)", muscleGroup: "Arms" },
  { name: "Hammer Curl (Dumbbell)", muscleGroup: "Arms" },
  { name: "Hammer Curl (Cable)", muscleGroup: "Arms" },
  { name: "Preacher Curl (Barbell)", muscleGroup: "Arms" },
  { name: "Preacher Curl (Dumbbell)", muscleGroup: "Arms" },
  { name: "Preacher Curl (Machine)", muscleGroup: "Arms" },
  { name: "Concentration Curl (Dumbbell)", muscleGroup: "Arms" },
  { name: "Spider Curl (Dumbbell)", muscleGroup: "Arms" },
  { name: "Reverse Curl (Barbell)", muscleGroup: "Arms" },
  { name: "21s Bicep Curl (Barbell)", muscleGroup: "Arms" },
  { name: "Triceps Extension", muscleGroup: "Arms" },
  { name: "Triceps Extension (Machine)", muscleGroup: "Arms" },
  { name: "Triceps Extension (Cable)", muscleGroup: "Arms" },
  { name: "Overhead Triceps Extension (Dumbbell)", muscleGroup: "Arms" },
  { name: "Triceps Pushdown (Cable)", muscleGroup: "Arms" },
  { name: "Skullcrusher (Barbell)", muscleGroup: "Arms" },
  { name: "Skullcrusher (Dumbbell)", muscleGroup: "Arms" },
  { name: "Close-Grip Bench Press (Barbell)", muscleGroup: "Arms" },
  { name: "Seated Palms Up Wrist Curl (Dumbbell)", muscleGroup: "Arms" },
  { name: "Wrist Curl (Barbell)", muscleGroup: "Arms" },
  { name: "Reverse Wrist Curl (Barbell)", muscleGroup: "Arms" },

  // Core
  { name: "Sit Up", muscleGroup: "Core" },
  { name: "Decline Sit Up", muscleGroup: "Core" },
  { name: "Crunch", muscleGroup: "Core" },
  { name: "Cable Crunch", muscleGroup: "Core" },
  { name: "Plank", muscleGroup: "Core" },
  { name: "Side Plank", muscleGroup: "Core" },
  { name: "Hanging Leg Raise", muscleGroup: "Core" },
  { name: "Leg Raise", muscleGroup: "Core" },
  { name: "Russian Twist", muscleGroup: "Core" },
  { name: "Ab Wheel Rollout", muscleGroup: "Core" },
  { name: "Mountain Climber", muscleGroup: "Core" },
  { name: "Bicycle Crunch", muscleGroup: "Core" },
  { name: "Woodchopper (Cable)", muscleGroup: "Core" },

  // Cardio
  { name: "Running (Treadmill)", muscleGroup: "Cardio" },
  { name: "Cycling (Bike)", muscleGroup: "Cardio" },
  { name: "Rowing Machine", muscleGroup: "Cardio" },
  { name: "Elliptical", muscleGroup: "Cardio" },
  { name: "Stair Climber", muscleGroup: "Cardio" },
  { name: "Jump Rope", muscleGroup: "Cardio" },
  { name: "Walking", muscleGroup: "Cardio" },
  { name: "Swimming", muscleGroup: "Cardio" },

  // Other
  { name: "Farmer's Walk", muscleGroup: "Other" },
  { name: "Box Jump", muscleGroup: "Other" },
  { name: "Battle Ropes", muscleGroup: "Other" },
  { name: "Kettlebell Swing", muscleGroup: "Other" },
  { name: "Clean and Jerk", muscleGroup: "Other" },
  { name: "Snatch (Barbell)", muscleGroup: "Other" },
  { name: "Sled Push", muscleGroup: "Other" },
];
